---

helm_image: &helm_image
  image: lowess/helm:v2.14.2

cr_image: &cr_image
  image: lowess/chart-releaser:v0.2.3

cr_env: &cr_env
  environment:
    CR_OWNER: Lowess
    CR_CHARTS_REPO: https://lowess.github.io/helm-charts
    CR_GIT_REPO: helm-charts
    CR_PACKAGE_PATH: .cr-release-packages
    CR_INDEX_PATH: .cr-index
    CR_TOKEN:
      from_secret: github_token

when_promoted: &when_promoted
  when:
    event:
      - promote
    target:
      - production

kind: pipeline
name: helm-release
steps:
  - name: helm_lint
    <<: *helm_image
    commands:
      - helm lint charts/*

  - name: helm_package
    <<: *helm_image
    <<: *cr_env
    environment:
      CHARTS: $CHARTS
    commands:
      - mkdir -p $CR_PACKAGE_PATH
      - helm repo add lowess-helm-charts https://lowess.github.io/helm-charts/
      - for CHART in ${CHARTS//,/ }; do
      -   helm dependency update charts/$CHART
      -   helm package charts/$CHART --destination $CR_PACKAGE_PATH;
      - done
    <<: *when_promoted

  - name: release_charts
    <<: *cr_image
    <<: *cr_env
    commands:
      - cr upload
    <<: *when_promoted

  - name: generate_index
    <<: *cr_image
    <<: *cr_env
    commands:
      - mkdir -p $CR_INDEX_PATH
      - cr index
      - cat $CR_INDEX_PATH/index.yaml
    <<: *when_promoted

  - name: publish_index
    image: plugins/gh-pages
    environment:
      DRONE_REMOTE_URL: git@github.com:Lowess/helm-charts.git
    settings:
      username: Lowess
      ssh_key:
        from_secret: github_ssh_key
      pages_directory: .cr-index
    <<: *when_promoted

  - name: display_urls
    image: lowess/drone-tabulate
    <<: *cr_env
    settings:
      headers:
        - Name
        - URLs
      rows:
        -
          - Helm Repo
          - https://lowess.github.io/helm-charts
