apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "burrow.fullname" . }}
  labels:
    {{- include "burrow.labels" . | nindent 4 }}
data:
  burrow.toml: |
    [general]
    pidfile={{ .Values.burrow.config.general.pidfile | default "burrow.pid" | quote }}

    [zookeeper]
    servers=[{{ join "," .Values.burrow.config.zookeeper.servers | quote }}]
    timeout={{ .Values.burrow.config.zookeeper.timout | default 6 }}
    root-path={{ .Values.burrow.config.zookeeper.rootPath | default "/burrow" | quote }}

    {{- $root := . }}
    {{ range $key, $value := .Values.burrow.config.cluster }}
    [cluster.{{ $key }}]
    class-name={{ $value.className | default "kafka" | quote }}
    servers=[{{ join "," $value.servers | quote }}]
    topic-refresh={{ $value.topicRefresh | default 30 }}
    offset-refresh={{ $value.offsetRefresh | default 30 }}
    {{- end }}

    {{ range $key, $value := .Values.burrow.config.consumer -}}
    [consumer.{{ $key }}]
    class-name={{ $value.className | default "kafka" | quote }}
    cluster="{{ $key }}"
    servers=[{{ join "," $value.servers | quote }}]
    group-blacklist={{ $value.groupBlacklist | default "^.*(console-consumer-|python-kafka-consumer-).*$" | quote }}
    group-whitelist={{ $value.groupwhitelist | default ".*" | quote }}
    {{- end }}

    [httpserver.default]
    address={{ .Values.burrow.config.httpserver.default.address | default ":8000" | quote }}

    {{ range $key, $value := .Values.burrow.config.notifier -}}
    [notifier.{{ $key }}]
    class-name={{ $value.className | quote }}
    interval={{ $value.interval | default 10 }}
    threshold={{ $value.threshold | default 1 }}
    group-blacklist={{ $value.groupBlacklist | default "^.*(console-consumer-|python-kafka-consumer-).*$" | quote }}
    group-whitelist={{ $value.groupWhitelist | default "^.*$" | quote }}
    {{- if $value.extras }}
    extras={{ $value.extras }}
    {{- end }}
    send-close={{ $value.sendClose | default true }}
    url-open={{ $value.urlOpen | quote }}
    url-close={{ $value.urlClose | quote }}
    template-open={{  printf "%s/%s" $root.Values.burrow.templateDir $value.templateOpen | quote }}
    template-close={{  printf "%s/%s" $root.Values.burrow.templateDir $value.templateClose | quote }}
    {{- end }}

    [logging]
    level={{ .Values.burrow.config.logging.level | default "info" | quote }}
