{{- if (not (empty .Values.burrow.templates)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "burrow.fullname" . }}-templates
  labels:
    {{- include "burrow.labels" . | nindent 4 }}
data:
{{- $root := . -}}
{{- range $key, $value := .Values.burrow.templates }}
  {{ $key }}: {{ toYaml $value | default "{}" | indent 4 }}
{{- end -}}
{{- end -}}
